# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ipr_barycentricRational <- function(x, y, order) {
    .Call(`_interpolators_ipr_barycentricRational`, x, y, order)
}

eval_barycentricRational <- function(ipr_xptr, x, derivative) {
    .Call(`_interpolators_eval_barycentricRational`, ipr_xptr, x, derivative)
}

