# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ipr_barycentricRational <- function(x, y, order) {
    .Call(`_interpolators_ipr_barycentricRational`, x, y, order)
}

eval_barycentricRational <- function(ipr_xptr, x, derivative) {
    .Call(`_interpolators_eval_barycentricRational`, ipr_xptr, x, derivative)
}

ipr_catmullRom <- function(X, closed, alpha) {
    .Call(`_interpolators_ipr_catmullRom`, X, closed, alpha)
}

eval_catmullRom <- function(ipr_xptr, s, derivative) {
    .Call(`_interpolators_eval_catmullRom`, ipr_xptr, s, derivative)
}

ipr_Makima <- function(x, y) {
    .Call(`_interpolators_ipr_Makima`, x, y)
}

eval_makima <- function(ipr_xptr, x, derivative) {
    .Call(`_interpolators_eval_makima`, ipr_xptr, x, derivative)
}

ipr_PCHIP <- function(x, y) {
    .Call(`_interpolators_ipr_PCHIP`, x, y)
}

eval_PCHIP <- function(ipr_xptr, x, derivative) {
    .Call(`_interpolators_eval_PCHIP`, ipr_xptr, x, derivative)
}

